name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          cd ezgenerator
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ezgenerator:${{ github.sha }} .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/ezgenerator:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/ezgenerator:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ezgenerator:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ezgenerator:latest
